import argparse
import math
import random
import time
from dataclasses import dataclass

import unreal


@dataclass(frozen=True)
class Config:
    level_path: str
    asset_dir: str
    mesh_name: str
    material_name: str
    actor_label_origin: str
    actor_label_prefix: str
    extra_count: int
    start_index: int
    layout: str
    diameter_cm: float
    color_r: float
    color_g: float
    color_b: float
    seed: int
    segment_min_cm: float
    segment_max_cm: float
    radius_min_cm: float
    radius_max_cm: float
    y_min: float
    y_max: float
    z_min: float
    z_max: float
    y_step_cm: float
    z_step_cm: float

    @property
    def material_path(self) -> str:
        return f"{self.asset_dir}/{self.material_name}"

    @property
    def mesh_path(self) -> str:
        return f"{self.asset_dir}/{self.mesh_name}"


def _log(message: str) -> None:
    unreal.log(f"[CreateRedSphereCourse] {message}")


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def _parse_args() -> Config:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--level", dest="level_path", default="/Game/SimBlank/Levels/SimBlank")
    parser.add_argument("--asset-dir", dest="asset_dir", default="/Game/AutoGenerated/RedSphere")
    parser.add_argument("--mesh-name", dest="mesh_name", default="SM_Sphere_1m")
    parser.add_argument("--material-name", dest="material_name", default="M_Red_Solid")
    parser.add_argument("--actor-origin", dest="actor_label_origin", default="RedSphere_1m_Origin")
    parser.add_argument("--actor-prefix", dest="actor_label_prefix", default="RedSphere_1m_Course_")
    parser.add_argument("--extra-count", dest="extra_count", type=int, default=8)
    parser.add_argument("--start-index", dest="start_index", type=int, default=1)
    parser.add_argument(
        "--layout",
        dest="layout",
        default="course",
        help="Placement layout: 'course' (forward path) or 'global' (evenly spread around origin with y>0).",
    )
    parser.add_argument("--diameter-cm", dest="diameter_cm", type=float, default=100.0)
    parser.add_argument("--color", dest="color", default="1,0,0")
    parser.add_argument("--seed", dest="seed", type=int, default=-1)
    parser.add_argument("--segment-min-cm", dest="segment_min_cm", type=float, default=1000.0)
    parser.add_argument("--segment-max-cm", dest="segment_max_cm", type=float, default=2000.0)
    parser.add_argument("--radius-min-cm", dest="radius_min_cm", type=float, default=4000.0)
    parser.add_argument("--radius-max-cm", dest="radius_max_cm", type=float, default=12000.0)
    parser.add_argument("--y-min", dest="y_min", type=float, default=300.0)
    parser.add_argument("--y-max", dest="y_max", type=float, default=2000.0)
    parser.add_argument("--z-min", dest="z_min", type=float, default=200.0)
    parser.add_argument("--z-max", dest="z_max", type=float, default=900.0)
    parser.add_argument("--y-step-cm", dest="y_step_cm", type=float, default=600.0)
    parser.add_argument("--z-step-cm", dest="z_step_cm", type=float, default=300.0)

    args, _ = parser.parse_known_args()

    try:
        r_str, g_str, b_str = (args.color or "").split(",")
        color_r = float(r_str)
        color_g = float(g_str)
        color_b = float(b_str)
    except Exception as exc:
        raise RuntimeError(f"Invalid --color '{args.color}'. Expected 'r,g,b' (e.g. '1,0,0').") from exc

    seed = int(time.time()) if args.seed is None or int(args.seed) < 0 else int(args.seed)

    return Config(
        level_path=args.level_path,
        asset_dir=args.asset_dir,
        mesh_name=args.mesh_name,
        material_name=args.material_name,
        actor_label_origin=args.actor_label_origin,
        actor_label_prefix=args.actor_label_prefix,
        extra_count=max(0, int(args.extra_count)),
        start_index=max(1, int(args.start_index)),
        layout=str(args.layout or "course").strip().lower(),
        diameter_cm=float(args.diameter_cm),
        color_r=color_r,
        color_g=color_g,
        color_b=color_b,
        seed=seed,
        segment_min_cm=float(args.segment_min_cm),
        segment_max_cm=float(args.segment_max_cm),
        radius_min_cm=float(args.radius_min_cm),
        radius_max_cm=float(args.radius_max_cm),
        y_min=float(args.y_min),
        y_max=float(args.y_max),
        z_min=float(args.z_min),
        z_max=float(args.z_max),
        y_step_cm=float(args.y_step_cm),
        z_step_cm=float(args.z_step_cm),
    )


def _ensure_directory(asset_dir: str) -> None:
    if unreal.EditorAssetLibrary.does_directory_exist(asset_dir):
        return
    _require(unreal.EditorAssetLibrary.make_directory(asset_dir), f"Failed to create directory: {asset_dir}")


def _create_or_load_asset(asset_path: str, asset_name: str, asset_dir: str, asset_class, factory) -> object:
    if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        asset = unreal.EditorAssetLibrary.load_asset(asset_path)
        _require(asset is not None, f"Failed to load asset: {asset_path}")
        return asset
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    asset = asset_tools.create_asset(asset_name, asset_dir, asset_class, factory)
    _require(asset is not None, f"Failed to create asset: {asset_path}")
    return asset


def _load_asset_if_exists(asset_path: str) -> object | None:
    if not unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        return None
    asset = unreal.EditorAssetLibrary.load_asset(asset_path)
    _require(asset is not None, f"Failed to load asset: {asset_path}")
    return asset


def _build_solid_color_material(cfg: Config) -> object:
    material = _create_or_load_asset(
        cfg.material_path,
        cfg.material_name,
        cfg.asset_dir,
        unreal.Material,
        unreal.MaterialFactoryNew(),
    )

    unreal.MaterialEditingLibrary.delete_all_material_expressions(material)
    color_expr = unreal.MaterialEditingLibrary.create_material_expression(
        material,
        unreal.MaterialExpressionConstant3Vector,
        -200,
        0,
    )
    _require(color_expr is not None, "Failed to create Constant3Vector expression")
    color_expr.constant = unreal.LinearColor(cfg.color_r, cfg.color_g, cfg.color_b, 1.0)
    _require(
        unreal.MaterialEditingLibrary.connect_material_property(
            color_expr,
            "",
            unreal.MaterialProperty.MP_BASE_COLOR,
        ),
        "Failed to connect Constant3Vector to BaseColor",
    )
    unreal.MaterialEditingLibrary.recompile_material(material)

    _require(
        unreal.EditorAssetLibrary.save_asset(cfg.material_path, only_if_is_dirty=False),
        f"Failed to save material: {cfg.material_path}",
    )
    return material


def _build_sphere_static_mesh(cfg: Config) -> object:
    radius_cm = max(0.01, cfg.diameter_cm / 2.0)
    dyn_mesh = unreal.new_object(unreal.DynamicMesh)
    _require(dyn_mesh is not None, "Failed to allocate DynamicMesh")

    prim_opts = unreal.GeometryScriptPrimitiveOptions()
    unreal.GeometryScript_Primitives.append_sphere_lat_long(
        dyn_mesh,
        prim_opts,
        unreal.Transform(),
        radius_cm,
        12,
        24,
    )

    static_mesh = _load_asset_if_exists(cfg.mesh_path)
    if static_mesh is None:
        _require(
            hasattr(unreal, "GeometryScript_NewAssetUtils"),
            "Missing GeometryScript_NewAssetUtils (GeometryScripting plugin/editor module not available).",
        )
        create_opts = unreal.GeometryScriptCreateNewStaticMeshAssetOptions()
        result = unreal.GeometryScript_NewAssetUtils.create_new_static_mesh_asset_from_mesh(
            dyn_mesh,
            cfg.mesh_path,
            create_opts,
        )
        if isinstance(result, tuple):
            static_mesh = result[0]
            outcome = next((x for x in result if isinstance(x, unreal.GeometryScriptOutcomePins)), None)
            if outcome is not None:
                _require(outcome == unreal.GeometryScriptOutcomePins.SUCCESS, f"CreateNewStaticMeshAssetFromMesh failed: {outcome}")
        else:
            static_mesh = result
        _require(static_mesh is not None, f"Failed to create static mesh: {cfg.mesh_path}")
    else:
        copy_opts = unreal.GeometryScriptCopyMeshToAssetOptions()
        write_lod = unreal.GeometryScriptMeshWriteLOD()
        result = unreal.GeometryScript_AssetUtils.copy_mesh_to_static_mesh(
            dyn_mesh,
            static_mesh,
            copy_opts,
            write_lod,
            True,
        )
        if isinstance(result, tuple):
            outcome = next((x for x in result if isinstance(x, unreal.GeometryScriptOutcomePins)), None)
            if outcome is not None:
                _require(outcome == unreal.GeometryScriptOutcomePins.SUCCESS, f"CopyMeshToStaticMesh failed: {outcome}")

    _require(
        unreal.EditorAssetLibrary.save_asset(cfg.mesh_path, only_if_is_dirty=False),
        f"Failed to save static mesh: {cfg.mesh_path}",
    )
    return static_mesh


def _load_level(level_path: str) -> None:
    _require(unreal.EditorLevelLibrary.load_level(level_path), f"Failed to load level: {level_path}")


def _find_actor_by_label(label: str):
    for existing in unreal.EditorLevelLibrary.get_all_level_actors():
        try:
            if existing.get_actor_label() == label:
                return existing
        except Exception:
            continue
    return None


def _spawn_or_update_sphere(label: str, location: unreal.Vector, static_mesh: object, material: object) -> None:
    actor = _find_actor_by_label(label)

    if actor is None:
        actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
            unreal.StaticMeshActor,
            location,
            unreal.Rotator(0.0, 0.0, 0.0),
            False,
        )
        _require(actor is not None, f"Failed to spawn StaticMeshActor for '{label}'")
        actor.set_actor_label(label)

    actor.set_actor_location(location, False, False)

    smc = actor.get_component_by_class(unreal.StaticMeshComponent)
    _require(smc is not None, f"StaticMeshComponent not found on actor '{label}'")
    smc.set_static_mesh(static_mesh)
    smc.set_material(0, material)


def _clamp(value: float, min_value: float, max_value: float) -> float:
    return max(min_value, min(max_value, value))


def _generate_course_locations(cfg: Config) -> list[unreal.Vector]:
    rng = random.Random(cfg.seed)

    segment_min = min(cfg.segment_min_cm, cfg.segment_max_cm)
    segment_max = max(cfg.segment_min_cm, cfg.segment_max_cm)

    y_min = min(cfg.y_min, cfg.y_max)
    y_max = max(cfg.y_min, cfg.y_max)
    z_min = min(cfg.z_min, cfg.z_max)
    z_max = max(cfg.z_min, cfg.z_max)

    y = rng.uniform(max(1.0, y_min), y_max)
    z = rng.uniform(max(1.0, z_min), z_max)
    x = 0.0

    locations: list[unreal.Vector] = []
    for _ in range(int(cfg.extra_count)):
        x += rng.uniform(segment_min, segment_max)
        y = _clamp(y + rng.uniform(-abs(cfg.y_step_cm), abs(cfg.y_step_cm)), max(1.0, y_min), y_max)
        z = _clamp(z + rng.uniform(-abs(cfg.z_step_cm), abs(cfg.z_step_cm)), max(1.0, z_min), z_max)
        locations.append(unreal.Vector(x, y, z))
    return locations


def _generate_global_locations(cfg: Config) -> list[unreal.Vector]:
    if int(cfg.extra_count) <= 0:
        return []

    rng = random.Random(cfg.seed)
    radius_min = min(cfg.radius_min_cm, cfg.radius_max_cm)
    radius_max = max(cfg.radius_min_cm, cfg.radius_max_cm)

    y_min = max(1.0, min(cfg.y_min, cfg.y_max))
    y_max = max(y_min, max(cfg.y_min, cfg.y_max))

    angle_offset = rng.uniform(0.0, math.tau)
    step = math.tau / float(int(cfg.extra_count))

    locations: list[unreal.Vector] = []
    for i in range(int(cfg.extra_count)):
        theta = angle_offset + (i * step)
        r = rng.uniform(radius_min, radius_max)
        x = math.cos(theta) * r
        z = math.sin(theta) * r
        y = rng.uniform(y_min, y_max)
        locations.append(unreal.Vector(x, y, z))
    return locations


def _generate_locations(cfg: Config) -> list[unreal.Vector]:
    if cfg.layout in ("course", "path", "forward"):
        return _generate_course_locations(cfg)
    if cfg.layout in ("global", "scatter", "ring", "radial"):
        return _generate_global_locations(cfg)
    raise RuntimeError(f"Unknown --layout '{cfg.layout}'. Expected 'course' or 'global'.")


def main() -> None:
    cfg = _parse_args()

    _log(f"Level: {cfg.level_path}")
    _log(f"Asset dir: {cfg.asset_dir}")
    _log(f"Mesh: {cfg.mesh_path} (diameter_cm={cfg.diameter_cm})")
    _log(f"Material: {cfg.material_path} (color={cfg.color_r},{cfg.color_g},{cfg.color_b})")
    _log(f"Origin: {cfg.actor_label_origin} @ (0,0,0)")
    _log(f"Extra: count={cfg.extra_count} prefix='{cfg.actor_label_prefix}' start_index={cfg.start_index} seed={cfg.seed}")
    _log(f"Layout: {cfg.layout}")
    _log(f"Constraints: y>0 (y_min={cfg.y_min}, y_max={cfg.y_max})")

    _ensure_directory(cfg.asset_dir)
    material = _build_solid_color_material(cfg)
    static_mesh = _build_sphere_static_mesh(cfg)

    _load_level(cfg.level_path)

    _spawn_or_update_sphere(cfg.actor_label_origin, unreal.Vector(0.0, 0.0, 0.0), static_mesh, material)

    for index, location in enumerate(_generate_locations(cfg), start=int(cfg.start_index)):
        label = f"{cfg.actor_label_prefix}{index:02d}"
        _log(f"Place {label} at ({location.x:.2f},{location.y:.2f},{location.z:.2f})")
        _spawn_or_update_sphere(label, location, static_mesh, material)

    _require(unreal.EditorLevelLibrary.save_current_level(), "Failed to save current level")
    _log("Success")


if __name__ == "__main__":
    main()
