"""
Desired behavior:
- Provide one shared runtime message contract for tooling and Unreal WebSocket traffic.
- Keep message building/parsing deterministic so controller, sampler, bridge, and UE client stay aligned.
- Keep wire-level decisions centralized (type names, required envelope fields, image bytes encoding).

Interfaces:
- This module is imported by `UE_Tooling/WebSocket/ws_bridge.py`, controller tooling, and sampler tooling.
- Callers use `make_*` helpers to build outbound messages and `loads_message` to parse inbound messages.
- All messages use one envelope shape: `type`, `run_id`, `schema_version`, `seq`, `timestamp`, `payload`.

Assumptions:
- v1 image payload transport is JSON-safe base64 (`payload.image_bytes_b64`) for cross-language simplicity.
- Message IDs are UUID strings and are generated by tooling when absent.
- Type labels are uppercase canonical tokens.

Success conditions:
- Callers can create/parse all v1 message categories with no ad-hoc shape logic.
- Message helpers include traceability fields required by run validation.
- Protocol constants are reusable by schema validation and bridge gating logic.
"""

from __future__ import annotations

import base64
import json
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

SCRIPT_NAME = "protocol"
SCRIPT_VERSION = "1.0.0"
SCRIPT_DATE = "2026-03-13"

SCHEMA_VERSION_V1 = "1.0"

TYPE_SET_CONFIG = "SET_CONFIG"
TYPE_ACK = "ACK"
TYPE_ACK_RECEIVED = "ACK_RECEIVED"
TYPE_CONFIG_READY = "CONFIG_READY"
TYPE_ACK_APPLIED = "ACK_APPLIED"
TYPE_SPAWN_DRONES = "SPAWN_DRONES"
TYPE_CMD = "CMD"
TYPE_CAPTURE_NOW = "CAPTURE_NOW"
TYPE_OBS = "OBS"
TYPE_STATUS = "STATUS"
TYPE_ERROR = "ERROR"

ALL_TYPES = {
    TYPE_SET_CONFIG,
    TYPE_ACK,
    TYPE_ACK_RECEIVED,
    TYPE_CONFIG_READY,
    TYPE_ACK_APPLIED,
    TYPE_SPAWN_DRONES,
    TYPE_CMD,
    TYPE_CAPTURE_NOW,
    TYPE_OBS,
    TYPE_STATUS,
    TYPE_ERROR,
}

ACTION_TYPES = {
    TYPE_SPAWN_DRONES,
    TYPE_CMD,
    TYPE_CAPTURE_NOW,
}

CONFIG_ACK_TYPES = {
    TYPE_ACK,
    TYPE_ACK_RECEIVED,
}

CONFIG_READY_TYPES = {
    TYPE_CONFIG_READY,
    TYPE_ACK_APPLIED,
}

IMAGE_PAYLOAD_KEY = "image_bytes_b64"
IMAGE_BLOCK_KEY = "image"
IMAGE_BYTES_FIELD = "bytes_b64"


class ProtocolError(ValueError):
    """Raised when protocol payloads cannot be parsed or are structurally invalid."""


def utc_timestamp() -> str:
    """Return UTC timestamp in ISO-8601 format."""
    return datetime.now(tz=timezone.utc).isoformat()


def new_message_id() -> str:
    """Return a new deterministic-format UUID string for message tracking."""
    return str(uuid4())


def normalize_type(message_type: str) -> str:
    """Normalize message type to canonical uppercase token."""
    if not isinstance(message_type, str) or not message_type.strip():
        raise ProtocolError(f"Invalid message type: {message_type!r}")
    return message_type.strip().upper()


def _normalize_optional_string(value: str | None) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise ProtocolError(f"Expected optional string, got {type(value).__name__}")
    stripped = value.strip()
    return stripped if stripped else None


def make_envelope(
    *,
    message_type: str,
    run_id: str,
    payload: dict[str, Any],
    schema_version: str = SCHEMA_VERSION_V1,
    seq: int | None = None,
    timestamp: str | None = None,
    drone_id: str | None = None,
    capture_id: str | None = None,
    config_id: str | None = None,
    config_hash: str | None = None,
    message_id: str | None = None,
    in_reply_to: str | None = None,
) -> dict[str, Any]:
    """Build one protocol envelope."""
    normalized_type = normalize_type(message_type)
    normalized_run_id = _normalize_optional_string(run_id)
    if normalized_run_id is None:
        raise ProtocolError("run_id is required and must be non-empty")
    if not isinstance(payload, dict):
        raise ProtocolError("payload must be a dict")

    envelope: dict[str, Any] = {
        "type": normalized_type,
        "run_id": normalized_run_id,
        "schema_version": schema_version,
        "seq": int(seq) if seq is not None else None,
        "timestamp": timestamp or utc_timestamp(),
        "payload": payload,
        "message_id": _normalize_optional_string(message_id) or new_message_id(),
    }

    optional_fields = {
        "drone_id": _normalize_optional_string(drone_id),
        "capture_id": _normalize_optional_string(capture_id),
        "config_id": _normalize_optional_string(config_id),
        "config_hash": _normalize_optional_string(config_hash),
        "in_reply_to": _normalize_optional_string(in_reply_to),
    }
    for key, value in optional_fields.items():
        if value is not None:
            envelope[key] = value

    return envelope


def make_set_config(
    *,
    run_id: str,
    payload: dict[str, Any],
    seq: int | None = None,
    timestamp: str | None = None,
    message_id: str | None = None,
) -> dict[str, Any]:
    """Build canonical `SET_CONFIG` envelope."""
    return make_envelope(
        message_type=TYPE_SET_CONFIG,
        run_id=run_id,
        payload=payload,
        seq=seq,
        timestamp=timestamp,
        config_id=str(payload.get("config_id", "")) if isinstance(payload, dict) else None,
        config_hash=str(payload.get("config_hash", "")) if isinstance(payload, dict) else None,
        message_id=message_id,
    )


def make_action(
    *,
    action_type: str,
    run_id: str,
    payload: dict[str, Any],
    seq: int | None = None,
    drone_id: str | None = None,
    capture_id: str | None = None,
    in_reply_to: str | None = None,
) -> dict[str, Any]:
    """Build action envelope (`SPAWN_DRONES`, `CMD`, `CAPTURE_NOW`)."""
    normalized_action = normalize_type(action_type)
    if normalized_action not in ACTION_TYPES:
        raise ProtocolError(f"Unsupported action type: {normalized_action}")
    return make_envelope(
        message_type=normalized_action,
        run_id=run_id,
        payload=payload,
        seq=seq,
        drone_id=drone_id,
        capture_id=capture_id,
        in_reply_to=in_reply_to,
    )


def make_ack(
    *,
    run_id: str,
    ack_type: str = TYPE_ACK,
    payload: dict[str, Any] | None = None,
    seq: int | None = None,
    in_reply_to: str | None = None,
) -> dict[str, Any]:
    """Build ack envelope (`ACK` or `ACK_RECEIVED`)."""
    normalized_ack = normalize_type(ack_type)
    if normalized_ack not in CONFIG_ACK_TYPES:
        raise ProtocolError(f"Unsupported ack type: {normalized_ack}")
    return make_envelope(
        message_type=normalized_ack,
        run_id=run_id,
        payload=payload or {},
        seq=seq,
        in_reply_to=in_reply_to,
    )


def make_config_ready(
    *,
    run_id: str,
    payload: dict[str, Any],
    seq: int | None = None,
    in_reply_to: str | None = None,
) -> dict[str, Any]:
    """Build config-ready envelope (`CONFIG_READY`)."""
    return make_envelope(
        message_type=TYPE_CONFIG_READY,
        run_id=run_id,
        payload=payload,
        seq=seq,
        config_id=str(payload.get("config_id", "")),
        config_hash=str(payload.get("config_hash", "")),
        in_reply_to=in_reply_to,
    )


def dumps_message(message: dict[str, Any]) -> str:
    """Serialize envelope to deterministic JSON."""
    return json.dumps(message, separators=(",", ":"), sort_keys=True)


def loads_message(raw: str | bytes) -> dict[str, Any]:
    """Parse JSON payload into dict envelope."""
    if isinstance(raw, bytes):
        raw = raw.decode("utf-8")
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ProtocolError(f"Invalid JSON payload: {exc}") from exc
    if not isinstance(payload, dict):
        raise ProtocolError(f"Protocol payload must be dict, got {type(payload).__name__}")
    return payload


def is_action_type(message_type: str) -> bool:
    return normalize_type(message_type) in ACTION_TYPES


def is_config_ack_type(message_type: str) -> bool:
    return normalize_type(message_type) in CONFIG_ACK_TYPES


def is_config_ready_type(message_type: str) -> bool:
    return normalize_type(message_type) in CONFIG_READY_TYPES


def encode_image_bytes(image_bytes: bytes) -> str:
    """Encode image bytes into base64 text for JSON payload transport."""
    if not isinstance(image_bytes, (bytes, bytearray)):
        raise ProtocolError(f"image_bytes must be bytes-like, got {type(image_bytes).__name__}")
    return base64.b64encode(bytes(image_bytes)).decode("ascii")


def decode_image_bytes(payload: dict[str, Any]) -> bytes | None:
    """Decode base64 image payload when present."""
    if not isinstance(payload, dict):
        return None
    encoded = None
    image_block = payload.get(IMAGE_BLOCK_KEY)
    if isinstance(image_block, dict):
        encoded = image_block.get(IMAGE_BYTES_FIELD)
    if encoded is None:
        encoded = payload.get(IMAGE_PAYLOAD_KEY)
    if encoded is None:
        return None
    if not isinstance(encoded, str):
        raise ProtocolError(
            f"{IMAGE_BLOCK_KEY}.{IMAGE_BYTES_FIELD} or {IMAGE_PAYLOAD_KEY} must be string when present"
        )
    try:
        return base64.b64decode(encoded, validate=True)
    except Exception as exc:  # pragma: no cover - defensive parse error path
        raise ProtocolError(f"Invalid base64 image payload: {exc}") from exc
