import argparse
import json
import os
import re
import time
from dataclasses import dataclass
from pathlib import Path

import unreal


@dataclass(frozen=True)
class Config:
    level_path: str
    mesh_path: str
    output_dir: str
    pretty: bool

    @property
    def level_name(self) -> str:
        return (self.level_path or "").rstrip("/").split("/")[-1] or "Level"


def _log(message: str) -> None:
    unreal.log(f"[ExtractTargetsTorusAxes] {message}")


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def _parse_args() -> Config:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--level", dest="level_path", default="/Game/SimBlank/Levels/SimBlank")
    parser.add_argument("--mesh", dest="mesh_path", default="/Game/AutoGenerated/RedSphere/SM_Torus_1mOpening")
    parser.add_argument("--output-dir", dest="output_dir", default="")
    parser.add_argument("--pretty", dest="pretty", action="store_true", default=True)
    parser.add_argument("--compact", dest="pretty", action="store_false")

    args, _ = parser.parse_known_args()

    output_dir = str(args.output_dir or "").strip()
    _require(bool(output_dir), "--output-dir is required (absolute path to Path_Optimizer/course_model)")

    output_path = Path(output_dir).expanduser()
    _require(output_path.is_absolute(), f"--output-dir must be an absolute path: {output_path}")

    return Config(
        level_path=str(args.level_path),
        mesh_path=str(args.mesh_path),
        output_dir=str(output_path),
        pretty=bool(args.pretty),
    )


def _sanitize_filename(value: str) -> str:
    value = (value or "").strip()
    value = re.sub(r"[^A-Za-z0-9._-]+", "_", value)
    return value or "Level"


def _vec_xyz(vector: unreal.Vector) -> dict[str, float]:
    return {"x": float(vector.x), "y": float(vector.y), "z": float(vector.z)}


def _load_level(level_path: str) -> None:
    _require(unreal.EditorLevelLibrary.load_level(level_path), f"Failed to load level: {level_path}")


def _load_static_mesh(mesh_path: str) -> object:
    mesh = unreal.EditorAssetLibrary.load_asset(mesh_path)
    _require(mesh is not None, f"Failed to load mesh asset: {mesh_path}")
    return mesh


def _get_component_static_mesh(component: object) -> object | None:
    try:
        return component.get_editor_property("static_mesh")
    except Exception:
        return getattr(component, "static_mesh", None)


def _matches_mesh(component: object, target_mesh: object) -> bool:
    component_mesh = _get_component_static_mesh(component)
    if component_mesh is None:
        return False
    try:
        return component_mesh.get_path_name() == target_mesh.get_path_name()
    except Exception:
        return component_mesh == target_mesh


def _extract_targets(level_path: str, mesh_path: str) -> dict:
    # Course order is not defined yet. We return a deterministic ordering using a simple spatial heuristic
    # (sort by x, then y, then z). A future version can introduce an explicit course ordering rule.

    _load_level(level_path)
    target_mesh = _load_static_mesh(mesh_path)

    targets: list[dict] = []
    for actor in unreal.EditorLevelLibrary.get_all_level_actors():
        smc = None
        try:
            smc = actor.get_component_by_class(unreal.StaticMeshComponent)
        except Exception:
            smc = None

        if smc is None:
            continue

        if not _matches_mesh(smc, target_mesh):
            continue

        try:
            position = actor.get_actor_location()
            axis_x = actor.get_actor_forward_vector()
            axis_y = actor.get_actor_right_vector()
            axis_z = actor.get_actor_up_vector()
        except Exception as exc:
            raise RuntimeError(f"Failed to read actor transform vectors for actor '{actor}': {exc}") from exc

        try:
            actor_label = actor.get_actor_label()
        except Exception:
            actor_label = ""

        try:
            actor_path = actor.get_path_name()
        except Exception:
            actor_path = ""

        targets.append(
            {
                "actor_label": str(actor_label),
                "actor_path": str(actor_path),
                "position_cm": _vec_xyz(position),
                "axis_x": _vec_xyz(axis_x),
                "axis_y": _vec_xyz(axis_y),
                "axis_z": _vec_xyz(axis_z),
            }
        )

    targets.sort(key=lambda item: (item["position_cm"]["x"], item["position_cm"]["y"], item["position_cm"]["z"]))

    timestamp_human = time.strftime("%Y-%m-%dT%H:%M:%S")
    report_name = f"targets-{_sanitize_filename(level_path.rstrip('/').split('/')[-1])}-{time.strftime('%Y%m%d_%H%M%S')}"

    return {
        "name": report_name,
        "level": str(level_path),
        "mesh": str(mesh_path),
        "frame": "unreal",
        "units": "cm",
        "generated_at": timestamp_human,
        "targets": targets,
    }


def _write_report(report: dict, output_dir: str, *, pretty: bool) -> str:
    os.makedirs(output_dir, exist_ok=True)
    filename = f"{report['name']}.json"
    path = str(Path(output_dir) / filename)

    if bool(report.get("targets")) is False:
        raise RuntimeError("No matching torus targets found to write.")

    indent = 2 if pretty else None
    with open(path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=indent, sort_keys=False)
        f.write("\n")

    return path


def main() -> None:
    cfg = _parse_args()

    _log(f"Level: {cfg.level_path}")
    _log(f"Mesh:  {cfg.mesh_path}")
    _log(f"Out:   {cfg.output_dir}")

    report = _extract_targets(cfg.level_path, cfg.mesh_path)
    output_path = _write_report(report, cfg.output_dir, pretty=bool(cfg.pretty))
    _log(f"Targets found: {len(report.get('targets') or [])}")
    _log(f"Wrote: {output_path}")


if __name__ == "__main__":
    main()
