import argparse
from dataclasses import dataclass

import unreal


@dataclass(frozen=True)
class Config:
    level_path: str
    asset_dir: str
    mesh_name: str
    material_name: str
    actor_label: str
    diameter_cm: float
    color_r: float
    color_g: float
    color_b: float
    steps_phi: int
    steps_theta: int

    @property
    def material_path(self) -> str:
        return f"{self.asset_dir}/{self.material_name}"

    @property
    def mesh_path(self) -> str:
        return f"{self.asset_dir}/{self.mesh_name}"


def _log(message: str) -> None:
    unreal.log(f"[CreateRedSphere] {message}")


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def _parse_args() -> Config:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--level", dest="level_path", default="/Game/SimBlank/Levels/SimBlank")
    parser.add_argument("--asset-dir", dest="asset_dir", default="/Game/AutoGenerated/RedSphere")
    parser.add_argument("--mesh-name", dest="mesh_name", default="SM_Sphere_1m")
    parser.add_argument("--material-name", dest="material_name", default="M_Red_Solid")
    parser.add_argument("--actor-label", dest="actor_label", default="RedSphere_1m_Origin")
    parser.add_argument("--diameter-cm", dest="diameter_cm", type=float, default=100.0)
    parser.add_argument("--color", dest="color", default="1,0,0")
    parser.add_argument("--steps-phi", dest="steps_phi", type=int, default=12)
    parser.add_argument("--steps-theta", dest="steps_theta", type=int, default=24)

    args, _ = parser.parse_known_args()
    try:
        r_str, g_str, b_str = (args.color or "").split(",")
        color_r = float(r_str)
        color_g = float(g_str)
        color_b = float(b_str)
    except Exception as exc:
        raise RuntimeError(f"Invalid --color '{args.color}'. Expected 'r,g,b' (e.g. '1,0,0').") from exc

    return Config(
        level_path=args.level_path,
        asset_dir=args.asset_dir,
        mesh_name=args.mesh_name,
        material_name=args.material_name,
        actor_label=args.actor_label,
        diameter_cm=args.diameter_cm,
        color_r=color_r,
        color_g=color_g,
        color_b=color_b,
        steps_phi=args.steps_phi,
        steps_theta=args.steps_theta,
    )


def _ensure_directory(asset_dir: str) -> None:
    if unreal.EditorAssetLibrary.does_directory_exist(asset_dir):
        return
    _require(unreal.EditorAssetLibrary.make_directory(asset_dir), f"Failed to create directory: {asset_dir}")


def _create_or_load_asset(asset_path: str, asset_name: str, asset_dir: str, asset_class, factory) -> object:
    if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        asset = unreal.EditorAssetLibrary.load_asset(asset_path)
        _require(asset is not None, f"Failed to load asset: {asset_path}")
        return asset
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    asset = asset_tools.create_asset(asset_name, asset_dir, asset_class, factory)
    _require(asset is not None, f"Failed to create asset: {asset_path}")
    return asset


def _load_asset_if_exists(asset_path: str) -> object | None:
    if not unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        return None
    asset = unreal.EditorAssetLibrary.load_asset(asset_path)
    _require(asset is not None, f"Failed to load asset: {asset_path}")
    return asset


def _build_solid_color_material(cfg: Config) -> object:
    material = _create_or_load_asset(
        cfg.material_path,
        cfg.material_name,
        cfg.asset_dir,
        unreal.Material,
        unreal.MaterialFactoryNew(),
    )

    unreal.MaterialEditingLibrary.delete_all_material_expressions(material)
    color_expr = unreal.MaterialEditingLibrary.create_material_expression(
        material,
        unreal.MaterialExpressionConstant3Vector,
        -200,
        0,
    )
    _require(color_expr is not None, "Failed to create Constant3Vector expression")
    color_expr.constant = unreal.LinearColor(cfg.color_r, cfg.color_g, cfg.color_b, 1.0)
    _require(
        unreal.MaterialEditingLibrary.connect_material_property(
            color_expr,
            "",
            unreal.MaterialProperty.MP_BASE_COLOR,
        ),
        "Failed to connect Constant3Vector to BaseColor",
    )
    unreal.MaterialEditingLibrary.recompile_material(material)

    _require(
        unreal.EditorAssetLibrary.save_asset(cfg.material_path, only_if_is_dirty=False),
        f"Failed to save material: {cfg.material_path}",
    )
    return material


def _build_sphere_static_mesh(cfg: Config) -> object:
    radius_cm = max(0.01, cfg.diameter_cm / 2.0)
    dyn_mesh = unreal.new_object(unreal.DynamicMesh)
    _require(dyn_mesh is not None, "Failed to allocate DynamicMesh")

    prim_opts = unreal.GeometryScriptPrimitiveOptions()
    unreal.GeometryScript_Primitives.append_sphere_lat_long(
        dyn_mesh,
        prim_opts,
        unreal.Transform(),
        radius_cm,
        int(cfg.steps_phi),
        int(cfg.steps_theta),
    )

    static_mesh = _load_asset_if_exists(cfg.mesh_path)
    if static_mesh is None:
        _require(
            hasattr(unreal, "GeometryScript_NewAssetUtils"),
            "Missing GeometryScript_NewAssetUtils (GeometryScripting plugin/editor module not available).",
        )
        create_opts = unreal.GeometryScriptCreateNewStaticMeshAssetOptions()
        result = unreal.GeometryScript_NewAssetUtils.create_new_static_mesh_asset_from_mesh(
            dyn_mesh,
            cfg.mesh_path,
            create_opts,
        )
        if isinstance(result, tuple):
            static_mesh = result[0]
            outcome = next((x for x in result if isinstance(x, unreal.GeometryScriptOutcomePins)), None)
            if outcome is not None:
                _require(outcome == unreal.GeometryScriptOutcomePins.SUCCESS, f"CreateNewStaticMeshAssetFromMesh failed: {outcome}")
        else:
            static_mesh = result
        _require(static_mesh is not None, f"Failed to create static mesh: {cfg.mesh_path}")
    else:
        copy_opts = unreal.GeometryScriptCopyMeshToAssetOptions()
        write_lod = unreal.GeometryScriptMeshWriteLOD()
        result = unreal.GeometryScript_AssetUtils.copy_mesh_to_static_mesh(
            dyn_mesh,
            static_mesh,
            copy_opts,
            write_lod,
            True,
        )

    if isinstance(result, tuple):
        outcome = None
        for item in result:
            if hasattr(unreal, "GeometryScriptOutcomePins") and isinstance(item, unreal.GeometryScriptOutcomePins):
                outcome = item
        if outcome is not None:
            _require(outcome == unreal.GeometryScriptOutcomePins.SUCCESS, f"CopyMeshToStaticMesh failed: {outcome}")

    _require(
        unreal.EditorAssetLibrary.save_asset(cfg.mesh_path, only_if_is_dirty=False),
        f"Failed to save static mesh: {cfg.mesh_path}",
    )
    return static_mesh


def _load_level(level_path: str) -> None:
    _require(unreal.EditorLevelLibrary.load_level(level_path), f"Failed to load level: {level_path}")


def _spawn_or_update_actor(cfg: Config, static_mesh: object, material: object) -> None:
    actor = None
    for existing in unreal.EditorLevelLibrary.get_all_level_actors():
        try:
            if existing.get_actor_label() == cfg.actor_label:
                actor = existing
                break
        except Exception:
            continue

    if actor is None:
        actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
            unreal.StaticMeshActor,
            unreal.Vector(0.0, 0.0, 0.0),
            unreal.Rotator(0.0, 0.0, 0.0),
            False,
        )
        _require(actor is not None, "Failed to spawn StaticMeshActor")
        actor.set_actor_label(cfg.actor_label)

    actor.set_actor_location(unreal.Vector(0.0, 0.0, 0.0), False, False)

    smc = actor.get_component_by_class(unreal.StaticMeshComponent)
    _require(smc is not None, "StaticMeshComponent not found on actor")
    smc.set_static_mesh(static_mesh)
    smc.set_material(0, material)


def main() -> None:
    cfg = _parse_args()

    _log(f"Level: {cfg.level_path}")
    _log(f"Asset dir: {cfg.asset_dir}")
    _log(f"Mesh: {cfg.mesh_path} (diameter_cm={cfg.diameter_cm})")
    _log(f"Material: {cfg.material_path} (color={cfg.color_r},{cfg.color_g},{cfg.color_b})")
    _log(f"Actor: {cfg.actor_label} @ (0,0,0)")

    _ensure_directory(cfg.asset_dir)
    material = _build_solid_color_material(cfg)
    static_mesh = _build_sphere_static_mesh(cfg)

    _load_level(cfg.level_path)
    _spawn_or_update_actor(cfg, static_mesh, material)

    _require(unreal.EditorLevelLibrary.save_current_level(), "Failed to save current level")
    _log("Success")


if __name__ == "__main__":
    main()
