dt: 0.05 # timer interval (seconds)
max_steps: 1000

drone:
  p_0: [0.0, 0.0, 0.0] # initial position (m)
  v_0: [0.0, 0.0, 0.0] # initial velocity (m/s)
  q_0: [1.0, 0.0, 0.0, 0.0] # initial attitude
  omega_0: [0.0, 0.0, 0.0] # initial angular rates (rad/s)

environment:
  temperature: 15.0 # degrees (C)
  pressure: 101325.0 # pressure (Pa)
  air_density: 1.225 # air density for drag force computation [kg/m^3]
  wind_velocity_world: [0.0, 0.0, 0.0] # ambient wind velocity in world frame [vx, vy, vz] [m/s]
  g: 9.81 # gravity (m/s^2)
