"""Configuration defaults for model training, evaluation, and inference."""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_ROOT = PROJECT_ROOT / "datasets"
MODEL_OUTPUT_DIR = PROJECT_ROOT / "artifacts/gate_pose"
MODEL_CHECKPOINT = MODEL_OUTPUT_DIR / "best.pt"

DEFAULT_TRAIN_RUNS = ["dataset_001/run_001"]
DEFAULT_TEST_RUNS = ["dataset_001/run_002"]

EPOCHS = 30
BATCH_SIZE = 2
VALIDATION_BATCH_SIZE = 4
WORKERS = 0
LOG_INTERVAL = 10
DEVICE = "auto"
SEED = 42
PATIENCE = 7
FREEZE_BACKBONE_EPOCHS = 2

INPUT_HEIGHT = 360
INPUT_WIDTH = 640
DATASET_FRAME_HEIGHT = 1080
DATASET_FRAME_WIDTH = 1920
PIXEL_SCALE_Y = INPUT_HEIGHT / DATASET_FRAME_HEIGHT
PIXEL_SCALE_X = INPUT_WIDTH / DATASET_FRAME_WIDTH

LEARNING_RATE = 1e-3
BACKBONE_LR_SCALE = 0.2
WEIGHT_DECAY = 1e-4
VALIDATION_FRACTION = 0.2
PARTIAL_FRAME_SAMPLING_WEIGHT = 2.0

SCORE_THRESHOLD = 0.7
DETECTIONS_PER_IMAGE = 12
BOX_NMS_THRESHOLD = 0.5
DUPLICATE_IOU_THRESHOLD = 0.25
DUPLICATE_CONTAINMENT_AREA_RATIO = 0.85
SUPPRESS_CONTAINED_DUPLICATES = True
PRETRAINED = True
ALLOW_RANDOM_INIT_ON_PRETRAINED_FAILURE = False

OVERLAY_COUNT = -1
THRESHOLD_SWEEP = [0.3, 0.5, 0.6, 0.7, 0.8, 0.9]

REFERENCE_INPUT_DIR = PROJECT_ROOT / "reference/test-frames"
REFERENCE_MODEL_DIR = PROJECT_ROOT / "artifacts/training-run-02"
VALIDATION_OUTPUT_ROOT = PROJECT_ROOT / "validation"
