import argparse
import random
import time
from dataclasses import dataclass

import unreal


@dataclass(frozen=True)
class Config:
    level_path: str
    asset_dir: str
    mesh_name: str
    material_name: str
    label_prefix: str
    inner_diameter_cm: float
    tube_radius_cm: float
    major_steps: int
    minor_steps: int
    seed: int

    @property
    def material_path(self) -> str:
        return f"{self.asset_dir}/{self.material_name}"

    @property
    def mesh_path(self) -> str:
        return f"{self.asset_dir}/{self.mesh_name}"


def _log(message: str) -> None:
    unreal.log(f"[ReplaceSpheresWithToruses] {message}")


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def _parse_args() -> Config:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--level", dest="level_path", default="/Game/SimBlank/Levels/SimBlank")
    parser.add_argument("--asset-dir", dest="asset_dir", default="/Game/AutoGenerated/RedSphere")
    parser.add_argument("--mesh-name", dest="mesh_name", default="SM_Torus_1mOpening")
    parser.add_argument("--material-name", dest="material_name", default="M_Red_Solid")
    parser.add_argument("--label-prefix", dest="label_prefix", default="RedSphere_1m_")
    parser.add_argument("--inner-diameter-cm", dest="inner_diameter_cm", type=float, default=100.0)
    parser.add_argument("--tube-radius-cm", dest="tube_radius_cm", type=float, default=10.0)
    parser.add_argument("--major-steps", dest="major_steps", type=int, default=48)
    parser.add_argument("--minor-steps", dest="minor_steps", type=int, default=24)
    parser.add_argument("--seed", dest="seed", type=int, default=-1)

    args, _ = parser.parse_known_args()

    seed = int(time.time()) if args.seed is None or int(args.seed) < 0 else int(args.seed)

    return Config(
        level_path=str(args.level_path),
        asset_dir=str(args.asset_dir),
        mesh_name=str(args.mesh_name),
        material_name=str(args.material_name),
        label_prefix=str(args.label_prefix),
        inner_diameter_cm=float(args.inner_diameter_cm),
        tube_radius_cm=float(args.tube_radius_cm),
        major_steps=max(3, int(args.major_steps)),
        minor_steps=max(3, int(args.minor_steps)),
        seed=seed,
    )


def _ensure_directory(asset_dir: str) -> None:
    if unreal.EditorAssetLibrary.does_directory_exist(asset_dir):
        return
    _require(unreal.EditorAssetLibrary.make_directory(asset_dir), f"Failed to create directory: {asset_dir}")


def _create_or_load_asset(asset_path: str, asset_name: str, asset_dir: str, asset_class, factory) -> object:
    if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        asset = unreal.EditorAssetLibrary.load_asset(asset_path)
        _require(asset is not None, f"Failed to load asset: {asset_path}")
        return asset
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    asset = asset_tools.create_asset(asset_name, asset_dir, asset_class, factory)
    _require(asset is not None, f"Failed to create asset: {asset_path}")
    return asset


def _load_asset_if_exists(asset_path: str) -> object | None:
    if not unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        return None
    asset = unreal.EditorAssetLibrary.load_asset(asset_path)
    _require(asset is not None, f"Failed to load asset: {asset_path}")
    return asset


def _load_or_create_red_material(cfg: Config) -> object:
    material = _create_or_load_asset(
        cfg.material_path,
        cfg.material_name,
        cfg.asset_dir,
        unreal.Material,
        unreal.MaterialFactoryNew(),
    )

    unreal.MaterialEditingLibrary.delete_all_material_expressions(material)
    color_expr = unreal.MaterialEditingLibrary.create_material_expression(
        material,
        unreal.MaterialExpressionConstant3Vector,
        -200,
        0,
    )
    _require(color_expr is not None, "Failed to create Constant3Vector expression")
    color_expr.constant = unreal.LinearColor(1.0, 0.0, 0.0, 1.0)
    _require(
        unreal.MaterialEditingLibrary.connect_material_property(
            color_expr,
            "",
            unreal.MaterialProperty.MP_BASE_COLOR,
        ),
        "Failed to connect Constant3Vector to BaseColor",
    )
    unreal.MaterialEditingLibrary.recompile_material(material)

    _require(
        unreal.EditorAssetLibrary.save_asset(cfg.material_path, only_if_is_dirty=False),
        f"Failed to save material: {cfg.material_path}",
    )
    return material


def _build_torus_static_mesh(cfg: Config) -> object:
    _require(cfg.inner_diameter_cm > 0.0, "--inner-diameter-cm must be > 0")
    _require(cfg.tube_radius_cm > 0.0, "--tube-radius-cm must be > 0")

    inner_radius_cm = cfg.inner_diameter_cm / 2.0
    major_radius_cm = inner_radius_cm + cfg.tube_radius_cm
    minor_radius_cm = cfg.tube_radius_cm

    dyn_mesh = unreal.new_object(unreal.DynamicMesh)
    _require(dyn_mesh is not None, "Failed to allocate DynamicMesh")

    prim_opts = unreal.GeometryScriptPrimitiveOptions()
    revolve_opts = unreal.GeometryScriptRevolveOptions()
    unreal.GeometryScript_Primitives.append_torus(
        dyn_mesh,
        prim_opts,
        unreal.Transform(),
        revolve_opts,
        float(major_radius_cm),
        float(minor_radius_cm),
        int(cfg.major_steps),
        int(cfg.minor_steps),
        unreal.GeometryScriptPrimitiveOriginMode.CENTER,
    )

    static_mesh = _load_asset_if_exists(cfg.mesh_path)
    if static_mesh is None:
        _require(
            hasattr(unreal, "GeometryScript_NewAssetUtils"),
            "Missing GeometryScript_NewAssetUtils (GeometryScripting plugin/editor module not available).",
        )
        create_opts = unreal.GeometryScriptCreateNewStaticMeshAssetOptions()
        result = unreal.GeometryScript_NewAssetUtils.create_new_static_mesh_asset_from_mesh(
            dyn_mesh,
            cfg.mesh_path,
            create_opts,
        )
        if isinstance(result, tuple):
            static_mesh = result[0]
            outcome = next((x for x in result if isinstance(x, unreal.GeometryScriptOutcomePins)), None)
            if outcome is not None:
                _require(outcome == unreal.GeometryScriptOutcomePins.SUCCESS, f"CreateNewStaticMeshAssetFromMesh failed: {outcome}")
        else:
            static_mesh = result
        _require(static_mesh is not None, f"Failed to create static mesh: {cfg.mesh_path}")
    else:
        copy_opts = unreal.GeometryScriptCopyMeshToAssetOptions()
        write_lod = unreal.GeometryScriptMeshWriteLOD()
        result = unreal.GeometryScript_AssetUtils.copy_mesh_to_static_mesh(
            dyn_mesh,
            static_mesh,
            copy_opts,
            write_lod,
            True,
        )
        if isinstance(result, tuple):
            outcome = next((x for x in result if isinstance(x, unreal.GeometryScriptOutcomePins)), None)
            if outcome is not None:
                _require(outcome == unreal.GeometryScriptOutcomePins.SUCCESS, f"CopyMeshToStaticMesh failed: {outcome}")

    _require(
        unreal.EditorAssetLibrary.save_asset(cfg.mesh_path, only_if_is_dirty=False),
        f"Failed to save static mesh: {cfg.mesh_path}",
    )
    return static_mesh


def _load_level(level_path: str) -> None:
    _require(unreal.EditorLevelLibrary.load_level(level_path), f"Failed to load level: {level_path}")


def _random_rotator(rng: random.Random) -> unreal.Rotator:
    pitch = rng.uniform(-180.0, 180.0)
    yaw = rng.uniform(-180.0, 180.0)
    roll = rng.uniform(-180.0, 180.0)
    return unreal.Rotator(pitch, yaw, roll)


def _replace_actors(cfg: Config, static_mesh: object, material: object) -> int:
    rng = random.Random(cfg.seed)
    updated = 0

    for actor in unreal.EditorLevelLibrary.get_all_level_actors():
        try:
            label = actor.get_actor_label()
        except Exception:
            continue

        if not label.startswith(cfg.label_prefix):
            continue

        smc = actor.get_component_by_class(unreal.StaticMeshComponent)
        if smc is None:
            continue

        smc.set_static_mesh(static_mesh)
        smc.set_material(0, material)

        rot = _random_rotator(rng)
        try:
            actor.set_actor_rotation(rot, False)
        except TypeError:
            actor.set_actor_rotation(rot, False, False)

        updated += 1

    return updated


def main() -> None:
    cfg = _parse_args()

    _log(f"Level: {cfg.level_path}")
    _log(f"Asset dir: {cfg.asset_dir}")
    _log(f"Mesh: {cfg.mesh_path} (inner_diameter_cm={cfg.inner_diameter_cm}, tube_radius_cm={cfg.tube_radius_cm})")
    _log(f"Material: {cfg.material_path} (solid red)")
    _log(f"Actor label prefix: '{cfg.label_prefix}'")
    _log(f"Rotation seed: {cfg.seed}")

    _ensure_directory(cfg.asset_dir)
    material = _load_or_create_red_material(cfg)
    static_mesh = _build_torus_static_mesh(cfg)

    _load_level(cfg.level_path)
    updated = _replace_actors(cfg, static_mesh, material)
    _require(updated > 0, f"No actors found with label prefix '{cfg.label_prefix}'")

    _require(unreal.EditorLevelLibrary.save_current_level(), "Failed to save current level")
    _log(f"Success (updated {updated} actors)")


if __name__ == "__main__":
    main()

